apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dot-hpa
  namespace: dotname
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dot-deployment
  minReplicas: 2  # Adjust as needed
  maxReplicas: 5  # Adjust as needed
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
      targetAverageUtilization: 70  # Adjust as needed
