apiVersion: apps/v1
kind: Deployment
metadata:
  name: dot-deployment
  namespace: dotname
  labels:
    app: dotnetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - eastus
      containers:
      - name: dotnetapp
        image: newcontainer12345.azurecr.io/newcontainer12345:2.2.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
      imagePullSecrets:
      - name: nani123
      tolerations:
      - key: "sample"
        operator: "Exists"
        effect: "NoSchedule"
