apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dot-role-binding
  namespace: dotname
subjects:
- kind: ServiceAccount
  name: dot-service-account
  namespace: dotname
roleRef:
  kind: Role
  name: dot-role
  apiGroup: rbac.authorization.k8s.io
